### ISSUE TITLE
The drop-down lang list takes a long time to open

### ISSUE THREAD

**Issue by klocus** [all2pie/angular-international-number#3]
As in the title: Opening the drop-down lang list takes a long time. Maybe the cause is using _*ngIf_ instead of a class that would hide and show the dropdown menu?

Currently _*ngIf_ removes all HTML code from the document structure, making the drop-down render again every time you click on the arrow. It seems to me that hiding this list using CSS would be more efficient, such as by _display: none_ and _display: block_.

**Comment by all2pie** [comment]
@klocus  can you open a Pull request with these changes and other improvements If possible?

**Comment by klocus** [comment]
@all2pie I will try to do it in my spare time :)
